### ISSUE TITLE
Misleading task names, change to invalid

### ISSUE THREAD

**Issue by seulsale** [IBM/zos_ims_operator#5]
Several tasks in `check_inputs` role say in the task name that are checking for valid conditions, but by looking at what they do (failing the playbook), it seems the correct word for the task names might be `invalid`. 

![image](https://github.com/IBM/zos_ims_operator/assets/20617822/1598719f-8ddf-4e68-9ac7-8931fe66d31e)

**Comment by adn1107** [comment]
Hi Sergio, good catch. Will get those change to 'invalid' in the next update.

**Comment by adn1107** [comment]
resolved in the next update.
